name: Discord Token

on:
  workflow_dispatch:

env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  TEST: ${{ vars.TEST }}
jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Version Check
        run: python --version
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install discord
          # pip install git+https://github.com/Rapptz/discord.py@async -U
      - name: Run Python
        run: 
          python AM.py
