name: Discord Token

on:
  workflow_dispatch:
env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Version Check
        run: python --version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install discord
      - name: Run Python
        run: 
          python AM.py
