name: Self Hosting Discord Bot

on:
  workflow_dispatch:
env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
jobs:
  setup:
    runs-on: self-hosted

          
  fix-ssl:
    runs-on: self-hosted
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
      - name: Run SSL code
        run:
          python ssl.py
      
  run-code:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Version Check
        run: python --version
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install discord
          pip install –upgrade certifi
      - name: Run Bot
        run: 
          python AM.py
