name: Testing

on:
  workflow_dispatch:
env:
  DISCORD_TOKEN: ${{ secrets.CLIENT_SECRET }}
jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Version Check
        run: python --version
      - name: Install dependencies
        run:
          pip install discord
      - name: Run Bot
        run: 
          python AM.py
